services:
  # Postgres Database
  database:
    image: postgres:17.3-alpine
    container_name: url-shortener-database
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  # Spring boot server
  backend:
    build: ./backend
    container_name: url-shortener-backend
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_URL: ${DB_URL}

  # Angular Frontend
  frontend:
    build: ./frontend
    container_name: url-shortener-frontend
    ports:
      - "4201:4200"
    depends_on:
      - backend
volumes:
  db:
