services:

  # Mongo Database
  database:
    image: mongo:latest
    container_name: url-shortener-database
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  # Spring boot server
  backend:
    build: ./backend
    container_name: url-shortener-backend
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_AUTH_DATABASE: ${DB_AUTH_DATABASE}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}

  # Angular Frontend
  frontend:
    build: ./frontend
    container_name: url-shortener-frontend
    ports:
      - "4201:4200"
    depends_on:
      - backend
volumes:
  mongodb_data:
